apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-blue
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd-counter-blue
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2024-01-12-counter-helm-example
    path: .
    helm:
      releaseName: counter-blue
      valuesObject:
        host: counter-blue.k8s.sikademo.com
        EXTRA_TEXT: "🔵"
        FONT_COLOR: "#ffffff"
        BACKGROUND_COLOR: "blue"
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: counter-blue-backend
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: counter-blue-frontend
      jsonPointers:
        - /spec/replicas
