apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-foo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: counter
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts
    path: ./charts/hello-world
    helm:
      valuesObject:
        host: hello-world-foo.k8s.sikademo.com
        image: sikalabs/hello-world-server:t-mobile
